name: Comware Coder Quasar Main CI

permissions: write-all

on:
  push:
    branches: [main]
    tags: [pre*, v*]
  pull_request:
    branches: [main]

jobs:
  get-info:
    runs-on: ubuntu-latest
    outputs:
      commit-hash: ${{ steps.git-info.outputs.commit-hash }}
    steps:
      - uses: actions/checkout@v4
      - name: Get git info
        id: git-info
        shell: bash
        run: |
          COMMIT_HASH=$(git rev-parse --short ${{ GITHUB.SHA }})
          echo "commit-hash=$COMMIT_HASH" >> $GITHUB_OUTPUT

  build:
    runs-on: windows-latest
    needs: get-info
    env:
      OUTPUT_FOLDER: ./dist/electron/Packaged
      RELEASE_FOLDER: ./release
    strategy:
      matrix:
        apiStyle: [HuggingFace, Linseer]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Setup pnpm
        uses: pnpm/action-setup@v3.0.0
        with:
          version: latest
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install
      - name: Publish Electron package
        run: pnpm run publish
      - name: List dist folder
        shell: bash
        run: |
          ls -l ./dist
          ls -l ./dist/electron
          ls -l ./dist/electron/Packaged
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cmw-coder-quasar_${{ needs.get-info.outputs.commit-hash }}_${{ GITHUB.RUN_NUMBER }}_${{ matrix.apiStyle }}_artifacts
          path: |
            ${{ env.OUTPUT_FOLDER }}/*.exe
            ${{ env.OUTPUT_FOLDER }}/*.exe.blockmap
            ${{ env.OUTPUT_FOLDER }}/release.yml
      - name: Upload other files
        uses: actions/upload-artifact@v4
        with:
          name: cmw-coder-quasar_${{ needs.get-info.outputs.commit-hash }}_${{ GITHUB.RUN_NUMBER }}_${{ matrix.apiStyle }}_other
          path: |
            ${{ env.OUTPUT_FOLDER }}/generic/
            ${{ env.OUTPUT_FOLDER }}/win-unpacked/
            ${{ env.OUTPUT_FOLDER }}/builder-debug.yml
            ${{ env.OUTPUT_FOLDER }}/builder-effective-config.yaml
      - name: Prepare for release
        if: ${{ startsWith(github.ref, 'refs/tags/pre') || startsWith(github.ref, 'refs/tags/v') }}
        shell: bash
        run: |
          mkdir -p ${{ env.RELEASE_FOLDER }}
          cp "${{ env.OUTPUT_FOLDER }}/*.exe" "${{ env.OUTPUT_FOLDER }}/*.exe.blockmap" "${{ env.OUTPUT_FOLDER }}/release.yml" ${{ env.RELEASE_FOLDER }}
      - name: Upload release
        if: ${{ startsWith(github.ref, 'refs/tags/pre') || startsWith(github.ref, 'refs/tags/v') }}
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: |
            ${{ env.RELEASE_FOLDER }}/*.exe
            ${{ env.RELEASE_FOLDER }}/*.exe.blockmap
            ${{ env.RELEASE_FOLDER }}/release.yml
          prerelease: ${{ startsWith(github.ref, 'refs/tags/pre') }}
