import { userInfo } from 'os';
import { NetworkZone } from 'shared/config';
import { AppConfig } from 'shared/types/AppConfig';

export const defaultAppConfigNetworkZoneMap: Record<NetworkZone, AppConfig> = {
  [NetworkZone.Normal]: {
    networkZone: NetworkZone.Unknown,
    username: userInfo().username,
    token: '',
    refreshToken: '',
    baseServerUrl: 'http://10.113.36.121',
    activeTemplate: 'Comware产品线',
    activeModel: 'CmwCoder',
    activeModelKey: 'CmwCoder',
    activeChat: 'default',
    separateTokens: {
      end: '<fim_middle>',
      middle: '<fim_suffix>',
      start: '<fim_prefix>',
    },
    completionConfigs: {
      function: {
        contextLimit: 1500,
        maxTokenCount: 1024,
        stopTokens: ['<fim_pad>', '<｜end▁of▁sentence｜>', '\n}'],
        suggestionCount: 1,
        temperature: 0.2,
      },
      line: {
        contextLimit: 1500,
        maxTokenCount: 64,
        stopTokens: ['<fim_pad>', '<｜end▁of▁sentence｜>', '\r\n', '\n'],
        suggestionCount: 1,
        temperature: 0.2,
      },
      snippet: {
        contextLimit: 1500,
        maxTokenCount: 96,
        stopTokens: ['<fim_pad>', '<｜end▁of▁sentence｜>', '}'],
        suggestionCount: 1,
        temperature: 0.2,
      },
    },
  },
  [NetworkZone.Public]: {
    networkZone: NetworkZone.Unknown,
    username: userInfo().username,
    token: '',
    refreshToken: '',
    baseServerUrl: 'http://rdee.h3c.com',
    activeTemplate: 'H3C通用',
    activeModel: '百业灵犀',
    activeModelKey: 'LS13B',
    activeChat: 'default',
    separateTokens: {
      end: '<fim_middle>',
      middle: '<fim_suffix>',
      start: '<fim_prefix>',
    },
    completionConfigs: {
      function: {
        contextLimit: 1500,
        maxTokenCount: 1024,
        stopTokens: ['<fim_pad>', '<｜end▁of▁sentence｜>', '\n}'],
        suggestionCount: 1,
        temperature: 0.2,
      },
      line: {
        contextLimit: 1500,
        maxTokenCount: 64,
        stopTokens: ['<fim_pad>', '<｜end▁of▁sentence｜>', '\r\n', '\n'],
        suggestionCount: 1,
        temperature: 0.2,
      },
      snippet: {
        contextLimit: 1500,
        maxTokenCount: 96,
        stopTokens: ['<fim_pad>', '<｜end▁of▁sentence｜>', '}'],
        suggestionCount: 1,
        temperature: 0.2,
      },
    },
  },
  [NetworkZone.Secure]: {
    networkZone: NetworkZone.Unknown,
    username: userInfo().username,
    token: '',
    refreshToken: '',
    baseServerUrl: 'http://10.113.12.206',
    activeTemplate: 'Comware产品线',
    activeModel: 'CmwCoder',
    activeModelKey: 'CmwCoder',
    activeChat: 'default',
    separateTokens: {
      end: '<fim_middle>',
      middle: '<fim_suffix>',
      start: '<fim_prefix>',
    },
    completionConfigs: {
      function: {
        contextLimit: 1500,
        maxTokenCount: 1024,
        stopTokens: ['<fim_pad>', '<｜end▁of▁sentence｜>', '\n}'],
        suggestionCount: 1,
        temperature: 0.2,
      },
      line: {
        contextLimit: 1500,
        maxTokenCount: 64,
        stopTokens: ['<fim_pad>', '<｜end▁of▁sentence｜>', '\r\n', '\n'],
        suggestionCount: 1,
        temperature: 0.2,
      },
      snippet: {
        contextLimit: 1500,
        maxTokenCount: 96,
        stopTokens: ['<fim_pad>', '<｜end▁of▁sentence｜>', '}'],
        suggestionCount: 1,
        temperature: 0.2,
      },
    },
  },
  [NetworkZone.Unknown]: {
    networkZone: NetworkZone.Unknown,
    username: userInfo().username,
    token: '',
    refreshToken: '',
    baseServerUrl: 'http://10.113.36.121',
    activeTemplate: 'Comware产品线',
    activeModel: 'CmwCoder',
    activeModelKey: 'CmwCoder',
    activeChat: 'default',
    separateTokens: {
      end: '<fim_middle>',
      middle: '<fim_suffix>',
      start: '<fim_prefix>',
    },
    completionConfigs: {
      function: {
        contextLimit: 1500,
        maxTokenCount: 1024,
        stopTokens: ['<fim_pad>', '<｜end▁of▁sentence｜>', '\n}'],
        suggestionCount: 1,
        temperature: 0.2,
      },
      line: {
        contextLimit: 1500,
        maxTokenCount: 64,
        stopTokens: ['<fim_pad>', '<｜end▁of▁sentence｜>', '\r\n', '\n'],
        suggestionCount: 1,
        temperature: 0.2,
      },
      snippet: {
        contextLimit: 1500,
        maxTokenCount: 96,
        stopTokens: ['<fim_pad>', '<｜end▁of▁sentence｜>', '}'],
        suggestionCount: 1,
        temperature: 0.2,
      },
    },
  },
};
